/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package etudiantInterfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class examen extends javax.swing.JFrame {
     private Connection connection;
     private ResultSet resultSet;
     private Timer countdownTimer;
private int secondsLeft;
    /**
     * Creates new form examen
     */
    public examen() {
        initComponents();
        this.setSize(740, 410);
        fetchQuestionFromDatabase(); 
        secondsLeft = 300; // 5 minutes
    countdownTimer = new Timer(1000, e -> updateCountdown());
    countdownTimer.start();
        
    }
   private void fetchQuestionFromDatabase() {
        try {
            String sql = "SELECT q.question, qr.reponsespossibles FROM question q " +
                         "JOIN question_reponses qr ON q.id = qr.question_id " +
                         "ORDER BY RANDOM() LIMIT 1"; // Fetch a random question for simplicity

            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                question.setText(resultSet.getString("question"));

                String reponsesPossibles = resultSet.getString("reponsespossibles");
                String[] reponsesArray = reponsesPossibles.split(",");

                rep1.setText(reponsesArray[0]);
                rep2.setText(reponsesArray[1]);
                rep3.setText(reponsesArray[2]);
                rep4.setText(reponsesArray[3]);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
   private void updateCountdown() {
        if (secondsLeft > 0) {
        secondsLeft--;
        int minutes = secondsLeft / 60;
        int seconds = secondsLeft % 60;
        String countdownText = String.format("%02d:%02d", minutes, seconds);
        
        // Mettez à jour votre interface utilisateur avec countdownText
        conteRebour.setText("Compte à rebours : " + countdownText);
    } else {
        // Le compte à rebours est terminé, vous pouvez prendre des mesures ici (par exemple, fermer la fenêtre)
        countdownTimer.stop();
         JOptionPane.showMessageDialog(this, "Le temps est écoulé !");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rep1 = new javax.swing.JCheckBox();
        rep2 = new javax.swing.JCheckBox();
        rep3 = new javax.swing.JCheckBox();
        rep4 = new javax.swing.JCheckBox();
        next = new javax.swing.JButton();
        conteRebour = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QCM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 10, 342, 35);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Question :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(47, 104, 56, 16);

        question.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(question);
        question.setBounds(97, 123, 467, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Cohcez la ou les bonnes réponses :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(47, 55, 231, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Suggestions :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(47, 160, 73, 16);

        rep1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(rep1);
        rep1.setBounds(113, 194, 421, 23);

        rep2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(rep2);
        rep2.setBounds(113, 223, 421, 23);

        rep3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        rep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep3ActionPerformed(evt);
            }
        });
        getContentPane().add(rep3);
        rep3.setBounds(113, 252, 421, 23);

        rep4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(rep4);
        rep4.setBounds(113, 281, 421, 23);

        next.setBackground(new java.awt.Color(51, 255, 0));
        next.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Suivant");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(600, 330, 79, 27);

        conteRebour.setForeground(new java.awt.Color(242, 242, 242));
        conteRebour.setText("conte à rebour");
        getContentPane().add(conteRebour);
        conteRebour.setBounds(490, 10, 210, 16);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\Pastel Light Blue Wallpaper High Resolution.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 740, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rep3ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        fetchQuestionFromDatabase(); // Fetch the next question when the button is clicked
    // Clear the selected checkboxes for the new question
    rep1.setSelected(false);
    rep2.setSelected(false);
    rep3.setSelected(false);
    rep4.setSelected(false);
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conteRebour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton next;
    private javax.swing.JLabel question;
    private javax.swing.JCheckBox rep1;
    private javax.swing.JCheckBox rep2;
    private javax.swing.JCheckBox rep3;
    private javax.swing.JCheckBox rep4;
    // End of variables declaration//GEN-END:variables
}
